# Generated by Django 4.0.5 on 2022-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_action_owner_step_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video',
            field=models.FileField(null=True, upload_to='media/courses/actions/videos/'),
        ),
    ]
