# Generated by Django 4.0.5 on 2022-08-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_action_owner_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='course',
        ),
        migrations.AddField(
            model_name='action',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.process'),
        ),
    ]
