# Generated by Django 4.0.5 on 2022-08-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_step_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='cover',
        ),
    ]
