# Generated by Django 4.0.5 on 2022-08-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_action_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='main_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='description',
            new_name='key_moment',
        ),
        migrations.AddField(
            model_name='action',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/courses/covers/static/'),
        ),
        migrations.AddField(
            model_name='step',
            name='key_moment_reason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='courses.action'),
        ),
    ]
