# Generated by Django 4.0.5 on 2022-08-11 15:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_main_text_action_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='title',
            new_name='step_title',
        ),
        migrations.AlterField(
            model_name='step',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='step_title', unique=True),
        ),
    ]
